name: Check typos

on:
#  push:
#    branches: [ "master", "main" ]
#  pull_request:
#    branches: [ "master", "main" ]
  workflow_call:

jobs:
  check-typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          # Important: fetch full history so typos can learn from corrections
          fetch-depth: 0

      - name: Install typos ğŸ› ï¸
        uses: crate-ci/typos@master
        with:
          version: v1.40.0
          config: .typos.toml
